
/*
DROP TABLE T_AULA19_AUTOR CASCADE CONSTRAINTS 
;
DROP TABLE T_AULA19_AUTOR_LIVRO CASCADE CONSTRAINTS 
;
DROP TABLE T_AULA19_CATEGORIA CASCADE CONSTRAINTS 
;
DROP TABLE T_AULA19_LIVRO CASCADE CONSTRAINTS 
;
*/

CREATE TABLE T_AULA19_AUTOR 
    ( 
     cd_autor NUMBER (3)  NOT NULL , 
     nm_primeiro_nome_autor VARCHAR2 (20)  NOT NULL , 
     nm_segundo_nome_autor VARCHAR2 (40)  NOT NULL , 
     nm_nome_completo VARCHAR2 (40)  NOT NULL , 
     ds_email VARCHAR2 (30)  NOT NULL 
    ) 
;

ALTER TABLE T_AULA19_AUTOR 
    ADD CONSTRAINT PK_AULA19_AUTOR PRIMARY KEY ( cd_autor ) ;


ALTER TABLE T_AULA19_AUTOR 
    ADD CONSTRAINT UN_AULA19_AUTOR_EMAIL UNIQUE ( ds_email ) ;

CREATE TABLE T_AULA19_AUTOR_LIVRO 
    ( 
     cd_autor NUMBER (3)  NOT NULL , 
     nr_isbn NUMBER (8)  NOT NULL , 
     st_autor_principal NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE T_AULA19_AUTOR_LIVRO 
    ADD CONSTRAINT CK_AULA19_AUTOR_LIVRO_STAT 
    CHECK (st_autor_principal in(1,2));

ALTER TABLE T_AULA19_AUTOR_LIVRO 
    ADD CONSTRAINT PK_AULA19_AUTOR_LIVRO PRIMARY KEY ( nr_isbn, cd_autor ) ;

CREATE TABLE T_AULA19_CATEGORIA 
    ( 
     cd_categoria NUMBER (3)  NOT NULL , 
     ds_sigla_categ CHAR (3)  NOT NULL , 
     ds_categoria VARCHAR2 (30)  NOT NULL 
    ) 
;


ALTER TABLE T_AULA19_CATEGORIA 
    ADD CONSTRAINT PK_AULA19_CATEGORIA PRIMARY KEY ( cd_categoria ) ;

ALTER TABLE T_AULA19_CATEGORIA 
    ADD CONSTRAINT UN_AULA19_CATEGORIA_SIGLA UNIQUE ( ds_sigla_categ ) ;

ALTER TABLE T_AULA19_CATEGORIA 
    ADD CONSTRAINT UN_AULA19_CATEGORIA_CATEGORIA UNIQUE ( ds_categoria ) ;

CREATE TABLE T_AULA19_LIVRO 
    ( 
     nr_isbn NUMBER (8)  NOT NULL , 
     cd_categoria NUMBER (3)  NOT NULL , 
     nm_titulo VARCHAR2 (50)  NOT NULL , 
     ds_sinopse VARCHAR2 (200)  NOT NULL , 
     nr_edicao NUMBER (2)  NOT NULL , 
     nr_ano NUMBER (4)  NOT NULL 
    ) 
;

ALTER TABLE T_AULA19_LIVRO 
    ADD CONSTRAINT CK_AULA19_LIVRO_EDICAO 
    CHECK (nr_edicao>0)
;

ALTER TABLE T_AULA19_LIVRO 
    ADD CONSTRAINT CK_AULA19_LIVRO_ANO 
    CHECK (nr_ano>0)
;

ALTER TABLE T_AULA19_LIVRO 
    ADD CONSTRAINT PK_AULA19_LIVRO PRIMARY KEY ( nr_isbn ) ;

ALTER TABLE T_AULA19_AUTOR_LIVRO 
    ADD CONSTRAINT FK_AULA19_AUTOR_LIVRO FOREIGN KEY 
    ( 
     cd_autor
    ) 
    REFERENCES T_AULA19_AUTOR 
    ( 
     cd_autor
    ) 
;

ALTER TABLE T_AULA19_LIVRO 
    ADD CONSTRAINT FK_AULA19_CATEG_LIVRO FOREIGN KEY 
    ( 
     cd_categoria
    ) 
    REFERENCES T_AULA19_CATEGORIA 
    ( 
     cd_categoria
    ) 
;

ALTER TABLE T_AULA19_AUTOR_LIVRO 
    ADD CONSTRAINT FK_AULA19_LIVRO_AUTOR FOREIGN KEY 
    ( 
     nr_isbn
    ) 
    REFERENCES T_AULA19_LIVRO 
    ( 
     nr_isbn
    ) 
;



