-------------------------------------------------------------
-- SCRIPT DDL (LINGUAGEM DE DEFINIÇÃO DE DADOS) PARA
-- CRIAR A ESTRUTURA DO BD
-- NOME ARQ: SCRIPT_DDL_SISTEMA_IMPLANTACAO_PROJETOS.SQL
-------------------------------------------------------------

-- Exclusão de tabelas
/*
DROP TABLE T_SIP_DEPARTAMENTO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_FUNCIONARIO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_DEPENDENTE CASCADE CONSTRAINTS;
DROP TABLE T_SIP_PROJETO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_IMPLANTACAO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_ESTADO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_CIDADE CASCADE CONSTRAINTS;
DROP TABLE T_SIP_TIPO_LOGRADOURO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_LOGRADOURO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_FUNC_ENDERECO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_ENDERECO CASCADE CONSTRAINTS;
DROP TABLE T_SIP_BAIRRO CASCADE CONSTRAINTS;
*/

-- CRIAR TABELA DEPARTAMENTO
CREATE TABLE T_SIP_DEPARTAMENTO
(
  cd_depto            NUMBER(2)     NOT NULL ,
  nm_depto            VARCHAR2(30)  NOT NULL
);
-- CONSTRAINT CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_DEPARTAMENTO
  ADD CONSTRAINT PK_SIP_DEPARTAMENTO
     PRIMARY KEY (cd_depto);
-- CONSTRAINT: UNIQUE
     ALTER TABLE T_SIP_DEPARTAMENTO
  ADD CONSTRAINT UN_SIP_DEPTO_NOME
          UNIQUE (nm_depto);

-- CRIAR TABELA FUNCIONARIO
CREATE TABLE T_SIP_FUNCIONARIO
(
  nr_matricula          NUMBER(5)       NOT NULL ,
  cd_depto              NUMBER(2)       NOT NULL ,
  nm_funcionario        VARCHAR2(50)    NOT NULL ,
  dt_nascimento         DATE                NULL ,
  dt_admissao           DATE            NOT NULL ,
  vl_salario            NUMBER(7,2)     NOT NULL
);
-- CONSTAINT CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_FUNCIONARIO
  ADD CONSTRAINT PK_SIP_FUNCIONARIO
     PRIMARY KEY (nr_matricula); 
     
-- CONSTRAINT CHECK
    ALTER TABLE T_SIP_FUNCIONARIO
    ADD CONSTRAINT CK_SIP_FUNC_SALARIO
    CHECK (VL_SALARIO >= 880);

-- CRIAR TABELA DEPENDENTE
CREATE TABLE T_SIP_DEPENDENTE
(
  cd_dependente         NUMBER(2)       NOT NULL ,
  nr_matricula          NUMBER(5)       NOT NULL ,
  nm_dependente         VARCHAR2(50)    NOT NULL ,
  dt_nascimento         DATE            NOT NULL
);
-- CONSTRAINT: CHAVE PRIMARIA
     ALTER TABLE T_SIP_DEPENDENTE
  ADD CONSTRAINT PK_SIP_DEPENDENTE
     PRIMARY KEY (cd_dependente , nr_matricula);

-- CRIAR A TABELA PROJETO
CREATE TABLE T_SIP_PROJETO
(
  cd_projeto            NUMBER(5)       NOT NULL ,
  nm_projeto            VARCHAR2(30)    NOT NULL ,
  dt_inicio             DATE            NOT NULL ,
  dt_termino            DATE                NULL
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_PROJETO
  ADD CONSTRAINT PK_SIP_PROJETO
     PRIMARY KEY (cd_projeto);
-- CONSTRAINT: UNIQUE
     ALTER TABLE T_SIP_PROJETO
  ADD CONSTRAINT UN_SIP_PROJETO_NOME
          UNIQUE (nm_projeto);
-- CONSTRAINT CHECK
     ALTER TABLE T_SIP_PROJETO
     ADD CONSTRAINT CK_SIP_PROJETO_DATA
     CHECK (DT_TERMINO > DT_INICIO);

-- CRIAR TABELA IMPLANTACAO
CREATE TABLE T_SIP_IMPLANTACAO
(
  cd_implantacao          NUMBER(6)     NOT NULL ,
  cd_projeto              NUMBER(5)     NOT NULL ,
  nr_matricula            NUMBER(5)     NOT NULL ,
  dt_entrada              DATE          NOT NULL ,
  dt_saida                DATE              NULL
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_IMPLANTACAO
  ADD CONSTRAINT PK_SIP_IMPLANTACAO
     PRIMARY KEY (cd_implantacao);
-- CONSTRAINT CHECK
    ALTER TABLE T_SIP_IMPLANTACAO
    ADD CONSTRAINT CK_SIP_IMPLANT_DATA
    CHECK (DT_SAIDA > DT_ENTRADA);
  
-- CRIAR TABELA ESTADO
CREATE TABLE T_SIP_ESTADO
(
  cd_estado           NUMBER(2)      NOT NULL ,
  nm_estado           VARCHAR2(30)   NOT NULL ,
  sg_estado           CHAR(2)        NOT NULL
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_ESTADO
  ADD CONSTRAINT PK_SIP_ESTADO
     PRIMARY KEY (cd_estado);
  
-- CRIAR TABELA CIDADE
CREATE TABLE  T_SIP_CIDADE
(
  cd_cidade           NUMBER(5)       NOT NULL ,
  cd_estado           NUMBER(2)       NOT NULL ,
  nm_estado           VARCHAR2(30)    NOT NULL
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_CIDADE
  ADD CONSTRAINT PK_SIP_CIDADE
     PRIMARY KEY (cd_cidade);
     
-- CRIAR TABELA BAIRRO
CREATE TABLE T_SIP_BAIRRO
(
  cd_bairro           NUMBER(5)       NOT NULL ,
  cd_cidade           NUMBER(5)       NOT NULL ,
  nm_bairro           VARCHAR2(30)    NOT NULL
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_BAIRRO
  ADD CONSTRAINT PK_SIP_BAIRRO
     PRIMARY KEY (cd_bairro);

-- CRIAR TABELA TIPO LOGRADOURO
CREATE TABLE T_SIP_TIPO_LOGRADOURO
(
  cd_tipo_logradouro    NUMBER(2)       NOT NULL ,
  nm_tipo_logradouro    VARCHAR2(25)    NOT NULL
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_TIPO_LOGRADOURO
  ADD CONSTRAINT PK_SIP_TIPO_LOGRADOURO
     PRIMARY KEY (cd_tipo_logradouro);

-- CRIAR TABELA LOGRADOURO
CREATE TABLE T_SIP_LOGRADOURO
(
  nr_cep                NUMBER(8)       NOT NULL ,
  cd_bairro             NUMBER(5)       NOT NULL ,
  cd_tipo_logradouro    NUMBER(2)       NOT NULL ,
  ds_logradouro         VARCHAR2(50)    NOT NULL
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_LOGRADOURO
  ADD CONSTRAINT PK_SIP_LOGRADOURO
     PRIMARY KEY (nr_cep);

-- CRIAR TABELA FUNC_ENDERECO
CREATE TABLE T_SIP_FUNC_ENDERECO
(
  nr_cep                NUMBER(8)       NOT NULL ,
  nr_matricula          NUMBER(5)       NOT NULL ,
  nr_logradouro         NUMBER(2)       NOT NULL ,
  ds_complemento        VARCHAR2(30)    NOT NULL 
);
-- CONSTRAINT: CHAVE PRIMÁRIA
     ALTER TABLE T_SIP_FUNC_ENDERECO
  ADD CONSTRAINT PK_SIP_FUNC_ENDERECO
     PRIMARY KEY (nr_cep, nr_matricula);
     
----------------------------
-- CHAVE ESTRANGEIRA - FK --
----------------------------
-- RELACIONAMENTO ENTRE FUNCIONARIO E DEPARTAMENTO
   ALTER TABLE T_SIP_FUNCIONARIO
   ADD CONSTRAINT FK_SIP_FUNC_DEPTO
   FOREIGN KEY (cd_depto)
   REFERENCES T_SIP_DEPARTAMENTO (cd_depto);
   
   -- RELACIONAMENTO ENTRE DEPENDENTE E FUNCIONARIO
   ALTER TABLE T_SIP_DEPENDENTE
   ADD CONSTRAINT FK_SIP_DEPENDENTE_FUNC
   FOREIGN KEY (nr_matricula)
   REFERENCES T_SIP_FUNCIONARIO (nr_matricula);
   
   --RELACIONAMENTO ENTRE IMPLANTACAO E PROJETO
   ALTER TABLE T_SIP_IMPLANTACAO
   ADD CONSTRAINT FK_SIP_IMPLANT_PROJETO
   FOREIGN KEY (cd_projeto)
   REFERENCES T_SIP_PROJETO (cd_projeto);
   
   -- RELACIONAMENTO ENTRE IMPLANTACAO E FUNCIONARIO
   ALTER TABLE T_SIP_IMPLANTACAO
   ADD CONSTRAINT FK_SIP_IMPLANT_FUNC
   FOREIGN KEY (nr_matricula)
   REFERENCES T_SIP_FUNCIONARIO (nr_matricula);
   
   -- RELACIONAMENTO ENTRE FUNC_ENDERECO E LOGRADOURO
   ALTER TABLE T_SIP_FUNC_ENDERECO
   ADD CONSTRAINT FK_SIP_FUNC_ENDE_LOGRAD
   FOREIGN KEY (nr_cep)
   REFERENCES T_SIP_LOGRADOURO (nr_cep);
   
   -- RELACIONAMENTO ENTRE FUNC ENDERECO E FUNCIONARIO
   ALTER TABLE T_SIP_FUNC_ENDERECO
   ADD CONSTRAINT FK_SIP_FUNC_ENDE_FUNCIONARIO
   FOREIGN KEY (nr_matricula)
   REFERENCES T_SIP_FUNCIONARIO (nr_matricula);
   
   -- RELACIONAMENTO ENTRE LOGRADOURO E TIPO DE LOGRADOURO
   ALTER TABLE T_SIP_LOGRADOURO
   ADD CONSTRAINT FK_SIP_LOGRAD_TIPO_LOG
   FOREIGN KEY (cd_tipo_logradouro)
   REFERENCES T_SIP_TIPO_LOGRADOURO (cd_tipo_logradouro);
   
   -- RELACIONAMENTO ENTRE LOGRADOURO E BAIRRO
   ALTER TABLE T_SIP_LOGRADOURO
   ADD CONSTRAINT FK_SIP_LOGRAD_BAIRRO
   FOREIGN KEY (cd_bairro)
   REFERENCES T_SIP_BAIRRO (cd_bairro);
   
   -- RELACIONAMENTO ENTRE BAIRRO E CIDADE
   ALTER TABLE T_SIP_BAIRRO
   ADD CONSTRAINT FK_SIP_BAIRRO_CIDADE
   FOREIGN KEY (cd_cidade)
   REFERENCES T_SIP_CIDADE (cd_cidade);
   
   -- RELACIONAMENTO ENTRE CIDADE E ESTADO
   ALTER TABLE T_SIP_CIDADE
   ADD CONSTRAINT FK_SIP_CIDADE_ESTADO
   FOREIGN KEY (cd_estado)
   REFERENCES T_SIP_ESTADO (cd_estado);