-------------------------------------------------------
--  AULA 24 - EXEMPLOS DE COMANDO SELECT COM JOIN
-------------------------------------------------------
-- ALTERAR O FORMATO DE DATA E HORA DESTA SESSAO
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH:MI';

-- EXEMPLO JUNÇÃO ENTRE DEPARTAMENTO E FUNCIONÁRIO
SELECT * FROM T_SIP_DEPARTAMENTO;

SELECT * FROM T_SIP_FUNCIONARIO;

SELECT F.NR_MATRICULA     "MATRICULA" ,
       F.CD_DEPTO  "COD. DEPTO" ,
       D.NM_DEPTO  "DEPARTATMENTO", 
       F.NM_FUNCIONARIO          "FUNCIONARIO"
  FROM T_SIP_DEPARTAMENTO D ,
       T_SIP_FUNCIONARIO  F
 WHERE D.CD_DEPTO = F.CD_DEPTO;   
 

-- CONSULTA AS TABELAS DEPARTAMENTO E FUNCIONARIO SEPARADAS
SELECT * FROM T_SIP_DEPARTAMENTO;
SELECT * FROM T_SIP_FUNCIONARIO;

-- EXEMPLO - CROSS JOIN (PRODUTO CARTESIANO)
SELECT * FROM T_SIP_DEPARTAMENTO, T_SIP_FUNCIONARIO;

-- UTILIZANDO O PADRÃO SQL/99
SELECT * 
   FROM T_SIP_DEPARTAMENTO CROSS JOIN T_SIP_FUNCIONARIO;

-- EXEMPLO - NATURAL JOIN
SELECT F.NR_MATRICULA     "MATRICULA" ,
       CD_DEPTO    "COD. DEPTO" ,
       D.NM_DEPTO  "DEPARTATMENTO", 
       F.NM_FUNCIONARIO          "FUNCIONARIO"
  FROM T_SIP_DEPARTAMENTO D NATURAL JOIN
       T_SIP_FUNCIONARIO  F;

-- EXEMPLO DA CLÁUSULA USING
SELECT F.NR_MATRICULA     "MATRICULA" ,
       CD_DEPTO    "COD. DEPTO" ,
       D.NM_DEPTO  "DEPARTATMENTO", 
       F.NM_FUNCIONARIO          "FUNCIONARIO"
  FROM T_SIP_DEPARTAMENTO D JOIN
       T_SIP_FUNCIONARIO  F
       USING (CD_DEPTO);

-- EXEMPLO COM INNER JOIN - PADRÃO SQL/99
  SELECT F.NR_MATRICULA     "MATRICULA" ,
         F.CD_DEPTO    "COD. DEPTO" ,
         D.NM_DEPTO  "DEPARTATMENTO", 
         F.NM_FUNCIONARIO          "FUNCIONARIO"
    FROM T_SIP_DEPARTAMENTO D INNER JOIN  T_SIP_FUNCIONARIO  F 
         ON ( D.CD_DEPTO = F.CD_DEPTO )
ORDER BY D.NM_DEPTO;
    
-- EXEMPLO COM INNER JOIN - PADRÃO ORACLE (ANTES SQL/99)
 SELECT F.NR_MATRICULA     "MATRICULA" ,
         F.CD_DEPTO    "COD. DEPTO" ,
         D.NM_DEPTO  "DEPARTATMENTO", 
         F.NM_FUNCIONARIO          "FUNCIONARIO"
    FROM T_SIP_DEPARTAMENTO D ,
         T_SIP_FUNCIONARIO  F 
   WHERE D.CD_DEPTO = F.CD_DEPTO 
ORDER BY D.NM_DEPTO;

-- EXEMPLO COM INNER JOIN - PADRÃO SQL/99 - CLÁUSULA USING
  SELECT F.NR_MATRICULA     "MATRICULA" ,
         CD_DEPTO    "COD. DEPTO" ,
         D.NM_DEPTO  "DEPARTATMENTO", 
         F.NM_FUNCIONARIO          "FUNCIONARIO"
    FROM T_SIP_DEPARTAMENTO D INNER JOIN  T_SIP_FUNCIONARIO  F 
         USING ( CD_DEPTO )
ORDER BY D.NM_DEPTO;

-- EXEMPLO COM INNER JOIN - PADRÃO SQL/99
-- RECUPERANDO OS DADOS DO FUNCIONÁRIO MOSTRANDO OS PROJETOS EM 
-- QUE ELE ESTÁ ATUANDO
  SELECT F.NR_MATRICULA     "MATRICULA" ,         
         F.NM_FUNCIONARIO          "FUNCIONARIO" ,
         P.NM_PROJETO       "PROJETO" ,
         I.DT_ENTRADA       "ENTRADA" ,
         I.DT_SAIDA         "SAIDA"
    FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
         ON ( P.CD_PROJETO = I.CD_PROJETO )
         INNER JOIN  T_SIP_FUNCIONARIO  F 
         ON ( F.NR_MATRICULA = I.NR_MATRICULA )
ORDER BY F.NM_FUNCIONARIO ;

-- EXEMPLO COM INNER JOIN - PADRÃO SQL/99 -  CLÁUSULA USING
  SELECT NR_MATRICULA       "MATRICULA" ,         
         F.NM_FUNCIONARIO          "FUNCIONARIO" ,
         P.NM_PROJETO       "PROJETO" ,
         I.DT_ENTRADA       "ENTRADA" ,
         I.DT_SAIDA         "SAIDA"
    FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
         USING ( CD_PROJETO )
         INNER JOIN  T_SIP_FUNCIONARIO  F 
         USING ( NR_MATRICULA )
ORDER BY F.NM_FUNCIONARIO ;

-- EXEMPLO COM INNER JOIN - PADRÃO ORACLE (ANTES SQL/99)
  SELECT F.NR_MATRICULA       "MATRICULA" ,         
         F.NM_FUNCIONARIO          "FUNCIONARIO" ,
         P.NM_PROJETO       "PROJETO" ,
         I.DT_ENTRADA       "ENTRADA" ,
         I.DT_SAIDA         "SAIDA"
    FROM T_SIP_PROJETO P,  T_SIP_FUNCIONARIO  F, T_SIP_IMPLANTACAO I
   WHERE P.CD_PROJETO = I.CD_PROJETO AND
         F.NR_MATRICULA = I.NR_MATRICULA
ORDER BY F.NM_FUNCIONARIO ;

-- EXEMPLO LEFT JOIN - PADRÃO SQL/99
SELECT   P.CD_PROJETO         "CODIGO" ,
         P.NM_PROJETO       "PROJETO" ,
         P.DT_INICIO        "DATA INICIO" ,
         I.NR_MATRICULA     "MATRÍCULA FUNCIONÁRIO" ,
         I.DT_ENTRADA       "ENTRADA"         
    FROM T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
         ON (P.CD_PROJETO = I.CD_PROJETO);
           
SELECT   P.CD_PROJETO         "CODIGO" ,
         P.NM_PROJETO       "PROJETO" ,
         P.DT_INICIO        "DATA INICIO" ,
         I.NR_MATRICULA     "MATRÍCULA FUNCIONÁRIO" ,
         I.DT_ENTRADA       "ENTRADA"         
    FROM T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
         ON (P.CD_PROJETO = I.CD_PROJETO)
   WHERE I.CD_PROJETO IS NULL ;
         
-- EXEMPLO LEFT JOIN - PADRÃO SQL/99 -  CLÁUSULA USING
SELECT   CD_PROJETO         "CODIGO" ,
         P.NM_PROJETO       "PROJETO" ,
         P.DT_INICIO        "DATA INICIO" ,
         I.NR_MATRICULA     "MATRÍCULA FUNCIONÁRIO" ,
         I.DT_ENTRADA       "ENTRADA"         
    FROM T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
         USING (CD_PROJETO);

-- EXEMPLO LEFT JOIN - PADRÃO ORACLE -  OPERADOR ( + )
SELECT   P.CD_PROJETO         "CODIGO" ,
         P.NM_PROJETO       "PROJETO" ,
         P.DT_INICIO        "DATA INICIO" ,
         I.NR_MATRICULA     "MATRÍCULA FUNCIONÁRIO" ,
         I.DT_ENTRADA       "ENTRADA"         
    FROM T_SIP_PROJETO P , T_SIP_IMPLANTACAO I
   WHERE P.CD_PROJETO  = I.CD_PROJETO (+);

-- EXEMPLO DE PROJETOS SEM IMPLANTAÇÕES
SELECT   P.CD_PROJETO         "CODIGO" ,
         P.NM_PROJETO       "PROJETO" ,
         P.DT_INICIO        "DATA INICIO" ,
         I.NR_MATRICULA     "MATRÍCULA FUNCIONÁRIO" ,
         I.DT_ENTRADA       "ENTRADA"         
    FROM T_SIP_PROJETO P , T_SIP_IMPLANTACAO I
   WHERE P.CD_PROJETO  = I.CD_PROJETO (+)
     AND I.CD_PROJETO IS NULL;

-- EXEMPLO RIGHT JOIN - PADRÃO SQL/99
SELECT   F.NR_MATRICULA     "MATRICULA FUNCIONÁRIO" ,
         I.CD_PROJETO       "CÓDIGO PROJETO" ,
         I.DT_ENTRADA       "DATA ENTRADA",
         I.DT_SAIDA         "DATA SAÍDA"
    FROM T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F
         ON (F.NR_MATRICULA = I.NR_MATRICULA); 

SELECT   F.NR_MATRICULA     "MATRICULA FUNCIONÁRIO" ,
         I.CD_PROJETO       "CÓDIGO PROJETO" ,
         I.DT_ENTRADA       "DATA ENTRADA",
         I.DT_SAIDA         "DATA SAÍDA"
    FROM T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F
         ON (F.NR_MATRICULA = I.NR_MATRICULA)
   WHERE I.NR_MATRICULA IS NULL;
         
-- EXEMPLO RIGHT JOIN - PADRÃO SQL/99 -  CLÁUSULA USING  
SELECT   NR_MATRICULA     "MATRICULA FUNCIONÁRIO" ,
         I.CD_PROJETO       "CÓDIGO PROJETO" ,
         I.DT_ENTRADA       "DATA ENTRADA",
         I.DT_SAIDA         "DATA SAÍDA"
    FROM T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F
         USING ( NR_MATRICULA ); 
         
-- EXEMPLO RIGHT JOIN - PADRÃO ORACLE -  OPERADOR ( + )
SELECT   F.NR_MATRICULA     "MATRICULA FUNCIONÁRIO" ,
         I.CD_PROJETO       "CÓDIGO PROJETO" ,         
         I.DT_ENTRADA       "DATA ENTRADA",
         I.DT_SAIDA         "DATA SAÍDA"
    FROM T_SIP_IMPLANTACAO I , T_SIP_FUNCIONARIO F
   WHERE I.NR_MATRICULA (+) = F.NR_MATRICULA;

-- MOSTRANDO APENAS OS FUNCIONÁRIOS SEM IMPLANTAÇÕES
SELECT   F.NR_MATRICULA     "MATRICULA FUNCIONÁRIO" ,
         I.CD_PROJETO       "CÓDIGO PROJETO" ,         
         I.DT_ENTRADA       "DATA ENTRADA",
         I.DT_SAIDA         "DATA SAÍDA"
    FROM T_SIP_IMPLANTACAO I , T_SIP_FUNCIONARIO F
   WHERE I.NR_MATRICULA (+) = F.NR_MATRICULA AND
         I.NR_MATRICULA IS NULL;
   
-- EXEMPLO FULL JOIN - PADRÃO SQL/99
SELECT   P.CD_PROJETO         "CODIGO" ,
         P.NM_PROJETO       "PROJETO" ,
         P.DT_INICIO        "DATA INICIO" ,
         I.NR_MATRICULA     "MATRÍCULA FUNCIONÁRIO" ,
         I.DT_ENTRADA       "ENTRADA"        
    FROM T_SIP_PROJETO P FULL OUTER JOIN T_SIP_IMPLANTACAO I
         ON (P.CD_PROJETO = I.CD_PROJETO) ;
          
-- EXEMPLO FULL JOIN - PADRÃO SQL/99 -  CLÁUSULA USING
SELECT   CD_PROJETO         "CODIGO" ,
         P.NM_PROJETO       "PROJETO" ,
         P.DT_INICIO        "DATA INICIO" ,
         I.NR_MATRICULA     "MATRÍCULA FUNCIONÁRIO" ,
         I.DT_ENTRADA       "ENTRADA"         
    FROM T_SIP_PROJETO P FULL OUTER JOIN T_SIP_IMPLANTACAO I
         USING (CD_PROJETO);         


-- EXEMPLO AUTOJUNÇAO (SELF JOIN) - PADRÃO ORACLE
SELECT FUNC.Matricula ,
       FUNC.NOME "FUNCIONÁRIO",
       FUNC.GERENTE  "COD. GERENTE",
       GER.NOME  "GERENTE"
FROM   T_AULA16_2_FUNCIONARIO FUNC ,
       T_AULA16_2_FUNCIONARIO GER
WHERE  GER.MATRICULA = FUNC.GERENTE;

-- EXEMPLO AUTOJUNÇAO (SELF JOIN) - PADRÃO SQL/99
SELECT FUNC.Matricula ,
       FUNC.NOME "FUNCIONÁRIO",
       FUNC.GERENTE  "COD. GERENTE",
       GER.NOME  "GERENTE"
FROM   T_AULA16_2_FUNCIONARIO FUNC INNER JOIN  T_AULA16_2_FUNCIONARIO GER
       ON (GER.MATRICULA = FUNC.GERENTE);

select * from T_AULA16_2_FUNCIONARIO;
