-- EXEMPLO DE SEQUENCIA

------------------------------------------------------
-- Criando sequencias para geração de autonumericos --
------------------------------------------------------
-- Sequencia tabela AUTOR
CREATE SEQUENCE SQ_AULA28_AUTOR
INCREMENT BY 1
START WITH 1
MAXVALUE 999
NOCACHE
NOCYCLE;
--
-- DROP SEQUENCE SQ_AULA28_AUTOR

SELECT SEQUENCE_NAME, 
       INCREMENT_BY, 
       MAX_VALUE, 
       LAST_NUMBER 
  FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME='SQ_AULA28_AUTOR';
 
INSERT INTO T_AULA28_AUTOR (CD_AUTOR, NM_PRIMEIRO_NOME_AUTOR, NM_SEGUNDO_NOME_AUTOR,NM_NOME_COMPLETO,DS_EMAIL) 
      VALUES (SQ_AULA28_AUTOR.nextval , 'RITA DE CASSIA','RODRIGUES','RITA DE CASSIA RODRIGUES','PROFARITA@FIAP.COM.BR');
INSERT INTO T_AULA28_AUTOR (CD_AUTOR, NM_PRIMEIRO_NOME_AUTOR, NM_SEGUNDO_NOME_AUTOR,NM_NOME_COMPLETO,DS_EMAIL) 
      VALUES (SQ_AULA28_AUTOR.nextval , 'RITA DE CASSIA2','RODRIGUES2','RITA DE CASSIA RODRIGUES2','PROFARITA2@FIAP.COM.BR');
COMMIT;     

SELECT * FROM T_AULA28_AUTOR;

SELECT SQ_AULA28_AUTOR.CURRVAL FROM DUAL;

SELECT SQ_AULA28_AUTOR.nextval FROM DUAL;
 
INSERT INTO T_AULA28_AUTOR (CD_AUTOR, NM_PRIMEIRO_NOME_AUTOR, NM_SEGUNDO_NOME_AUTOR,NM_NOME_COMPLETO,DS_EMAIL) 
      VALUES (SQ_AULA28_AUTOR.nextval , 'RITA DE CASSIA3','RODRIGUES3','RITA DE CASSIA RODRIGUES3','PROFARITA3@FIAP.COM.BR');