--------------------------------------------------------
--  AULA 31 - EXEMPLOS DE FUN합ES SQL / ORACLE
--------------------------------------------------------

-- FUN합ES DE CONVERS홒 DE ESCRITA
SELECT LOWER(F.NM_FUNCIONARIO)    "MINUSCULAS (LOWER)" ,
       UPPER(F.NM_FUNCIONARIO)    "MAIUSCULAS (UPPER)" ,
       INITCAP(F.NM_FUNCIONARIO)  "MAIUSCULA/MINUSCULA (INITCAP)" 
  FROM T_SIP_FUNCIONARIO F;

-- FUN합ES ASCII(X) E CHAR(X)
SELECT ASCII('R'), CHR(82) FROM DUAL;

-- FUN플O CONCAT(X,Y)
SELECT CONCAT(CONCAT(F.NR_MATRICULA,'-'),F.NM_FUNCIONARIO)           
  FROM T_SIP_FUNCIONARIO F;

-- FUN플O INSTR(X,STRING, INICIO, OCORRENCIA)  
SELECT F.NM_FUNCIONARIO                ,
       INSTR(F.NM_FUNCIONARIO,'A')     ,
       INSTR(F.NM_FUNCIONARIO,'A',3)   ,
       INSTR(F.NM_FUNCIONARIO,'A',3,2)
  FROM T_SIP_FUNCIONARIO F;
  
-- FUN플O LENGTH(X)  
SELECT F.NM_FUNCIONARIO , LENGTH(F.NM_FUNCIONARIO)    
  FROM T_SIP_FUNCIONARIO F;
  
-- FUN플O LPAD(X, LARGURA, STRING PREENCHIMENTO)  E  RPAD(X, LARGURA, STRING PREENCHIMENTO)
SELECT F.NM_FUNCIONARIO                ,
       F.VL_SALARIO             ,
       RPAD(F.NM_FUNCIONARIO,60)       ,
       RPAD(F.NM_FUNCIONARIO,60,'.')   ,
       LPAD(VL_SALARIO,10,'*')   
  FROM T_SIP_FUNCIONARIO F;

-- FUN플O NVL(X, VALOR) E NVL2(X, VALOR1, VALOR2)
SELECT F.DT_NASCIMENTO ,
       NVL(F.DT_NASCIMENTO,'01/01/1900'),
       NVL2(F.DT_NASCIMENTO,SYSDATE,'01/01/1900')       
  FROM T_SIP_FUNCIONARIO F;  

-- FUN플O REPLACE (X, STRING_BUSCA, STRING_SUBSITUICAO)
SELECT F.NM_FUNCIONARIO                ,
       REPLACE(F.NM_FUNCIONARIO,'A','*')
  FROM T_SIP_FUNCIONARIO F;
  
-- FUN플O SUBSTR(X, INICIO, COMPRIMENTO)
SELECT F.NM_FUNCIONARIO                ,
       SUBSTR(F.NM_FUNCIONARIO,3)      ,
       SUBSTR(F.NM_FUNCIONARIO,3, 5)      
  FROM T_SIP_FUNCIONARIO F;
  

-- ROUND(X,Y) , MOD(X,Y), TRUNC(X,Y), SQRT(X), ABS(X)
SELECT F.VL_SALARIO           ,
       ROUND(F.VL_SALARIO)    ,
       ROUND(F.VL_SALARIO,1)  ,
       TRUNC(F.VL_SALARIO)    ,
       TRUNC(F.VL_SALARIO,1)  ,
       MOD(F.VL_SALARIO,3)    ,
       ABS(F.VL_SALARIO)      ,
       SQRT(F.VL_SALARIO)
  FROM T_SIP_FUNCIONARIO F;

-- FUN플O TO_CHAR()
SELECT TO_CHAR(F.VL_SALARIO, 'L9999999.99') "SIMBOLO MOEDA LOCAL" ,
       TO_CHAR(F.NR_MATRICULA, '0099999')       
  FROM T_SIP_FUNCIONARIO F;

SELECT TO_CHAR(12345678, '0099999999') ,
       TO_CHAR(1234.56,'C99,999.99')  "SIMBOLO MOEDA ISO" ,
       TO_CHAR(-120.30,'99,999.99')
  FROM DUAL;
  
-- FUN플O TO_NUMBER()  
SELECT TO_NUMBER('103')      ,
       TO_NUMBER('103') + 30 ,
       TO_NUMBER('-$12,345.99','$99,999.99')
  FROM DUAL;

-- FUN플O CAST()
-- CONVERTER VALORES LITERAIS EM TIPOS ESPECIFICOS
SELECT 
        CAST(12345.67 AS VARCHAR2(10) ) ,        
        CAST('29/09/2013' AS DATE ) ,
        CAST(12345.678 AS NUMBER(10,2) ) 
  FROM DUAL;

-- CONVERTER VALORES DE COLUNA DE UM TIPO PARA OUTRO
SELECT 
       CAST (F.VL_SALARIO AS VARCHAR2(10) ) ,
       CAST (F.VL_SALARIO + 1000 AS NUMBER (8,2))
  FROM T_SIP_FUNCIONARIO F;
  

