ALTER TABLE T_AM_ART_CLIENTE
RENAME COLUMN cd_pessoa TO cd_cliente;

ALTER TABLE T_AM_ART_FORUM
RENAME COLUMN cd_pessoa TO cd_forum;

ALTER TABLE T_AM_ART_ADVOGADO
RENAME COLUMN cd_pessoa TO cd_advogado;

ALTER TABLE T_AM_ART_ESPECIALIDADE
RENAME COLUMN cd_pessoa TO cd_advogado;

ALTER TABLE T_AM_ART_HORA_ADVOGADO
RENAME COLUMN cd_pessoa TO cd_advogado;

ALTER TABLE T_AM_ART_PROCESSO
DROP CONSTRAINT FK_AM_ART_PROC_CLIENTE CASCADE;

ALTER TABLE T_AM_ART_PROCESSO
ADD CONSTRAINT FK_AM_ART_PROC_CLIENTE
FOREIGN KEY (cd_cliente)
REFERENCES T_AM_ART_CLIENTE (cd_cliente);

ALTER TABLE T_AM_ART_PROCESSO
MODIFY ds_processo VARCHAR2(60);