--------------------------------------------------------
--  AULA 29 - EXEMPLOS DE FUNÇÕES DE GRUPO E AGRUPAMENTO
--------------------------------------------------------
-- ALTERAR O FORMATO DE DATA E HORA DESTA SESSAO
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH:MI';

-- EXEMPLO COUNT()
SELECT CD_DEPTO, NM_DEPTO FROM T_SIP_DEPARTAMENTO;

SELECT COUNT(CD_DEPTO), count(*) FROM T_SIP_DEPARTAMENTO  ;

SELECT COUNT(*) FROM T_SIP_DEPARTAMENTO;

SELECT * FROM T_SIP_PROJETO;

SELECT COUNT(DT_TERMINO) FROM T_SIP_PROJETO;

SELECT COUNT(*), count(dt_termino) 
  FROM T_SIP_PROJETO
 WHERE DT_TERMINO IS NOT NULL ;
 
 SELECT COUNT(*) 
  FROM T_SIP_PROJETO
 WHERE DT_TERMINO IS  NULL ;
 
SELECT * FROM T_SIP_IMPLANTACAO;

SELECT COUNT(DISTINCT CD_PROJETO), count(*)
  FROM T_SIP_IMPLANTACAO ;


-- EXEMPLO SUM()
SELECT * FROM T_SIP_FUNCIONARIO;

SELECT SUM(VL_SALARIO)
  FROM T_SIP_FUNCIONARIO;

-- EXEMPLO AVG()
SELECT AVG(VL_SALARIO)
  FROM T_SIP_FUNCIONARIO;

-- EXEMPLO MIN()  
SELECT MIN(VL_SALARIO)
  FROM T_SIP_FUNCIONARIO;  

-- EXEMPLO MAX()
SELECT MAX(VL_SALARIO)
  FROM T_SIP_FUNCIONARIO;  

-- EXEMPLO STDDEV() 
SELECT STDDEV(VL_SALARIO)
  FROM T_SIP_FUNCIONARIO;  

-- EXEMPLO VARIANCE()
SELECT VARIANCE(VL_SALARIO)
  FROM T_SIP_FUNCIONARIO;  


-- AGRUPANDO VALORES
SELECT * FROM T_SIP_FUNCIONARIO ORDER BY CD_DEPTO;
SELECT * FROM T_SIP_DEPENDENTE;

-- AGRUPANDO LINHAS EM UMA ÚNICA TABELA
SELECT NR_MATRICULA, COUNT(CD_DEPENDENTE) "QTDE. FILHOS"
  FROM T_SIP_DEPENDENTE
GROUP BY NR_MATRICULA;

  SELECT AVG(VL_SALARIO)
    FROM T_SIP_FUNCIONARIO
GROUP BY CD_DEPTO; 

-- AGRUPANDO LINHAS EM VÁRIAS TABELAS

SELECT F.NM_FUNCIONARIO              "FUNCIONARIO"     ,
       D.NR_MATRICULA         "MATRICULA"       , 
       D.CD_DEPENDENTE        "CD. DEPENDENTE"  ,
       D.NM_DEPENDENTE        "DEPENDENTE"
  FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D
       ON (F.NR_MATRICULA = D.NR_MATRICULA);
       
SELECT F.NM_FUNCIONARIO              "FUNCIONARIO" ,
       D.NR_MATRICULA         "MATRICULA"   , 
       COUNT(D.NR_MATRICULA)  "QTDE. FILHOS"
  FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPENDENTE D
       ON (F.NR_MATRICULA = D.NR_MATRICULA)
GROUP BY F.NM_FUNCIONARIO, D.NR_MATRICULA;  

-- EXEMPLO UTILIZANDO HAVING
  SELECT CD_DEPTO , AVG(VL_SALARIO) "MÉDIA SALÁRIOS"
    FROM T_SIP_FUNCIONARIO
GROUP BY CD_DEPTO
  HAVING AVG(VL_SALARIO) > 2000
ORDER BY AVG(VL_SALARIO) DESC;





